server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/addressbook?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**